
<select id="<?= $this->getId();?>" name="<?= $this->getName(); ?>" multiple="multiple">class="<?= $this->getClass();?>"<?=($this->getRequired()) ? ' required':null ?><?= ($this->getDisabled()) ? ' disabled':null;?> <?= $this->getExtra(); ?>>
<?php foreach ($this->getOptions() as $value => $label): ?>
    <option value="<?= $value ?>"<?= (!in_array($value, $this->getValues())) ?: ' selected'?>><?= $label ?></option>
<?php endforeach; ?>
</select>