
<select id="<?= $this->getId();?>" name="<?= $this->getId(); ?>" class="<?= $this->getClass();?>"<?= ($this->getRequired()) ? 'required' : null; ?><?= ($this->getDisabled()) ? ' disabled' : null ;?> <?= $this->getExtra(); ?>>
<?php foreach ($this->getOptions() as $value => $label): ?>
    <option value="<?= $value ?>"<?= ($value != $this->getValue()) ?: ' selected'?>><?= $label ?></option>
<?php endforeach; ?>
</select>